{
	"version": 1620660420,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/boutonvitesse-sheet0.png",
		"images/boutonvitesse-sheet1.png",
		"images/bonusdoublescore-sheet0.png",
		"images/bonusdoublescore-sheet1.png",
		"images/bonustimer-sheet0.png",
		"images/bonustimer-sheet1.png",
		"images/scorer1-sheet0.png",
		"images/deadblock0-sheet0.png",
		"images/deadblock1-sheet0.png",
		"images/deadblock10-sheet0.png",
		"images/deadblock11-sheet0.png",
		"images/deadblock2-sheet0.png",
		"images/deadblock3-sheet0.png",
		"images/deadblock4-sheet0.png",
		"images/deadblock6-sheet0.png",
		"images/deadblock5-sheet0.png",
		"images/deadblock7-sheet0.png",
		"images/deadblock8-sheet0.png",
		"images/deadblock9-sheet0.png",
		"images/bloc-sheet0.png",
		"images/bloc-sheet1.png",
		"images/blocorigin-sheet0.png",
		"images/blocorigin-sheet1.png",
		"images/blocspawn-sheet0.png",
		"images/recettes-sheet0.png",
		"images/grid-sheet0.png",
		"images/poubelle-sheet0.png",
		"images/poubelle-sheet1.png",
		"images/recettedifficile-sheet0.png",
		"images/spawnbloc1-sheet0.png",
		"images/spawnbloc2-sheet0.png",
		"images/bordbug-sheet0.png",
		"images/chefshat-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground.png",
		"images/spawntapis1-sheet0.png",
		"images/sapwntapis2-sheet0.png",
		"images/respawntapis2-sheet0.png",
		"images/respawntapis-sheet0.png",
		"images/tapis1-sheet0.png",
		"images/poubellealiment-sheet0.png",
		"images/apparitionaliment1-sheet0.png",
		"images/collider-sheet0.png",
		"images/destroytapis-sheet0.png",
		"media/wrong.ogg",
		"media/poubelle.ogg",
		"media/clochette.m4a",
		"media/clochette.ogg",
		"media/timere.ogg",
		"media/tapis roulant.ogg",
		"media/bonusson.ogg",
		"media/bonusson.m4a",
		"media/temps en plus.ogg",
		"media/rotation-004.ogg",
		"media/rotation-003.ogg",
		"media/rotation-002.ogg",
		"media/rotation-001.ogg",
		"media/aliment pose .ogg",
		"media/selection 2.0.ogg",
		"media/selection 2.0.m4a",
		"media/passage 2.0.ogg",
		"media/passage 2.0.m4a",
		"media/musique phase 4 (169 bpm).ogg",
		"media/musique phase 1 (144 bpm) (1).ogg",
		"media/musique phase 2 (144 bpm) (1).ogg",
		"media/musique phase 3 (144 bpm) (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}